import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
    main: {
        backgroundColor: "#f6f9fc",
        fontFamily:
            '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
        direction: "rtl",
    },
    container: {
        backgroundColor: "#ffffff",
        padding: "20px auto",
        margin: "64px auto",
        maxWidth: "600px",
        direction: "rtl",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    content: {
        margin: "64px auto",
        maxWidth: "504px",
        direction: "rtl",
    },
    h1: {
        color: "#1a1a1a",
        fontSize: "28px",
        fontWeight: "bold",
        margin: "40px 0",
        padding: "0 40px",
        textAlign: "right",
        direction: "rtl",
    },
    text: {
        color: "#484848",
        fontSize: "16px",
        lineHeight: "26px",
        textAlign: "right",
        padding: "0 40px",
        margin: "16px 0",
        direction: "rtl",
    },
    buttonContainer: {
        padding: "27px 40px",
        direction: "rtl",
    },
    button: {
        backgroundColor: "#000000",
        borderRadius: "8px",
        color: "#fff",
        fontSize: "18px",
        fontWeight: "bold",
        textDecoration: "none",
        textAlign: "center",
        display: "block",
        width: "100%",
        padding: "16px 0",
        direction: "rtl",
    },
    list: {
        padding: "0 40px",
        margin: "16px 0",
        direction: "rtl",
    },
    listItem: {
        color: "#484848",
        fontSize: "15px",
        lineHeight: "28px",
        textAlign: "right",
        margin: "4px 0",
        direction: "rtl",
    },
    tipBox: {
        backgroundColor: "#f0f9ff",
        border: "2px solid #bfdbfe",
        borderRadius: "8px",
        padding: "16px 24px",
        margin: "24px 40px",
        width: "calc(100% - 80px)",
        direction: "rtl",
    },
    tipText: {
        color: "#1e40af",
        fontSize: "15px",
        lineHeight: "24px",
        textAlign: "right",
        margin: "0",
        direction: "rtl",
    },
    signature: {
        color: "#1a1a1a",
        fontSize: "16px",
        lineHeight: "24px",
        textAlign: "right",
        padding: "0 40px",
        margin: "24px 0 0 0",
        direction: "rtl",
    },
    hr: {
        borderColor: "#e6ebf1",
        margin: "32px 40px",
        width: "calc(100% - 80px)",
        direction: "rtl",
    },
    footer: {
        padding: "0 40px",
        margin: "16px 0",
        direction: "rtl",
    },
    footerText: {
        color: "#484848",
        fontSize: "14px",
        lineHeight: "22px",
        textAlign: "right",
        margin: "8px 0",
        direction: "rtl",
    },
    footerLink: {
        color: "#000000",
        fontSize: "14px",
        fontWeight: "bold",
        textDecoration: "none",
        borderBottom: "2px solid #000000",
        direction: "rtl",
    },
    companyInfo: {
        padding: "0 40px",
        direction: "rtl",
    },
    companyText: {
        color: "#8898aa",
        fontSize: "12px",
        lineHeight: "20px",
        textAlign: "right",
        margin: "4px 0",
        direction: "rtl",
    },
    link: {
        color: "#8898aa",
        textDecoration: "underline",
        direction: "rtl",
    },
    infoSection: {
        padding: "0 40px",
        marginBottom: "20px",
        direction: "rtl",
    },
    label: {
        color: "#71717a",
        fontSize: "13px",
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: "0.5px",
        margin: "0 0 6px 0",
        direction: "rtl",
    },
    value: {
        color: "#18181b",
        fontSize: "16px",
        lineHeight: "24px",
        margin: "0",
        textAlign: "right",
        direction: "rtl",
    },
    emailLink: {
        color: "#2563eb",
        textDecoration: "none",
        fontWeight: "500",
        direction: "rtl",
    },
    timeWasterBox: {
        backgroundColor: "#fafafa",
        border: "1px solid #e4e4e7",
        borderRadius: "6px",
        padding: "16px",
        marginTop: "8px",
        direction: "rtl",
    },
    timeWasterText: {
        color: "#18181b",
        fontSize: "15px",
        lineHeight: "24px",
        margin: "0",
        whiteSpace: "pre-wrap",
        direction: "rtl",
    },
};
